# Generated by Django 3.2.9 on 2022-01-25 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mv', '0003_auto_20220125_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voter_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
