# Generated by Django 3.2.9 on 2022-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0004_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review_point',
            field=models.FloatField(default=0, verbose_name='리뷰평점'),
        ),
    ]
